-- puœciæ jako dba
GRANT SELECT ON &&CUTTER_SCHEMA..hd_uzytkownik_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_kontrahent_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_asortyment_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_grupaAsortymentowa_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_rodzajdokumentu_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_typdokumentu_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_faktura_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_faktura_poz_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_typmagazynu_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_magazyn_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_zamowienie_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_zamowienie_poz_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_zamowienie_poz_dod_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_dokumentymag_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_dokumentymag_poz_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_kontrakt_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_kontrakt_poz_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_produkty_view TO &&hd_role;
GRANT SELECT ON &&CUTTER_SCHEMA..hd_pozycje_obrobki_view TO &&hd_role;

--jako dba
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_UZYTKOWNIK FOR  &&CUTTER_SCHEMA..hd_uzytkownik_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_KONTRAHENT FOR  &&CUTTER_SCHEMA..hd_kontrahent_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_ASORTYMENT FOR  &&CUTTER_SCHEMA..hd_asortyment_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_GRUPAASORTYMENTOWA FOR  &&CUTTER_SCHEMA..hd_grupaAsortymentowa_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_RODZAJDOKUMENTU FOR  &&CUTTER_SCHEMA..hd_rodzajdokumentu_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_TYPDOKUMENTU FOR  &&CUTTER_SCHEMA..hd_typdokumentu_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_FAKTURASPRZEDAZY FOR  &&CUTTER_SCHEMA..hd_faktura_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_FSPOZYCJE FOR  &&CUTTER_SCHEMA..hd_faktura_poz_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_TYPMAGAZYNU FOR  &&CUTTER_SCHEMA..hd_typmagazynu_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_MAGAZYNOWE FOR  &&CUTTER_SCHEMA..hd_magazyn_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_ZLECENIE FOR  &&CUTTER_SCHEMA..hd_zamowienie_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_ZLECENIE_POZYCJE FOR  &&CUTTER_SCHEMA..hd_zamowienie_poz_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_ZLECENIE_POZYCJE_DODATKOWE FOR  &&CUTTER_SCHEMA..hd_zamowienie_poz_dod_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_MAGAZYNOWY FOR  &&CUTTER_SCHEMA..hd_dokumentymag_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_MAGAZYN_POZYCJE FOR  &&CUTTER_SCHEMA..hd_dokumentymag_poz_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..D_KONTRAKT FOR  &&CUTTER_SCHEMA..hd_kontrakt_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_KONTRAKT_POZYCJE FOR  &&CUTTER_SCHEMA..hd_kontrakt_poz_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_PRODUKTY FOR  &&CUTTER_SCHEMA..hd_produkty_view;
CREATE OR REPLACE SYNONYM &&HD_SCHEMA..F_POZYCJE_OBROBKI FOR  &&CUTTER_SCHEMA..hd_pozycje_obrobki_view;

