-- puœciæ jako dba
CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_UZYTKOWNIK" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_UZYTKOWNIK_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_UZYTKOWNIK" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_KONTRAHENT" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_KONTRAHENT_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_KONTRAHENT" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_KARTOTEKA" ("LOG_DATE" DATE, "ID" VARCHAR2(500), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_KARTOTEKA_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_KARTOTEKA" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_GRUPATOWAROWA" ("LOG_DATE" DATE, "ID" VARCHAR2(40), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_GRUPATOWAROWA_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_GRUPATOWAROWA" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_FAKTURA" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_FAKTURA_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_FAKTURA" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_MAGAZYN" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_MAGAZYN_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_MAGAZYN" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_ZAMOWIENIE" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_ZAMOWIENIE_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_ZAMOWIENIE" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_DOKUMENTYMAG" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_DOKUMENTYMAG_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_DOKUMENTYMAG" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_KONTRAKT" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_KONTRAKT_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_KONTRAKT" ("ID", "LOG_DATE");

CREATE TABLE &&CUTTER_SCHEMA.."HD_LOG_PRODUKT" ("LOG_DATE" DATE, "ID" NUMBER(10,0), "ACTION" VARCHAR2(1 BYTE));
CREATE INDEX &&CUTTER_SCHEMA.."HD_LOG_PRODUKT_IND1" ON &&CUTTER_SCHEMA.."HD_LOG_PRODUKT" ("ID", "LOG_DATE");
